# Dicionário com os times da Premier League
premier_league_teams = {
    "Arsenal": "Arsenal",
    "Aston Villa": "Aston Villa",
    "AFC Bournemouth": "AFC Bournemouth",
    "Brentford": "Brentford",
    "Brighton & Hove Albion": "Brighton & Hove Albion",
    "Burnley": "Burnley",
    "Chelsea": "Chelsea",
    "Crystal Palace": "Crystal Palace",
    "Everton": "Everton",
    "Fulham": "Fulham",
    "Liverpool": "Liverpool",
    "Luton Town": "Luton Town",
    "Manchester City": "Manchester City",
    "Manchester United": "Manchester United",
    "Newcastle United": "Newcastle United",
    "Nottingham Forest": "Nottingham Forest",
    "Sheffield United": "Sheffield United",
    "Tottenham Hotspur": "Tottenham Hotspur",
    "West Ham United": "West Ham United",
    "Wolverhampton Wanderers": "Wolverhampton Wanderers",
    "Stoke City": "Stoke City",
    "Southampton": "Southampton",
    "Swansea City": "Swansea City",
    "West Bromwich Albion": "West Bromwich Albion",
    "Leeds United": "Leeds United",
    "Cardiff City": "Cardiff City",
    "Leicester City": "Leicester City",
    "Norwich City": "Norwich City",
    "Huddersfield Town": "Huddersfield Town",
    "Watford": "Watford"
}

# Dicionário com os times do Brasileirao serie A
brasileirao_a_teams = {
    'América Mineiro': 'América Mineiro',
    'Santos': 'Santos',
    'Sport Recife': 'Sport Recife',
    'Atlético GO': 'Atlético GO',
    'Paraná': 'Paraná',
    'Chapecoense': 'Chapecoense',
    'Botafogo': 'Botafogo',
    'Ponte Preta': 'Ponte Preta',
    'Vasco da Gama': 'Vasco da Gama',
    'Goiás': 'Goiás',
    'Ceará': 'Ceará',
    'Coritiba': 'Coritiba',
    'Atlético Mineiro': 'Atlético Mineiro',
    'Cuiabá': 'Cuiabá',
    'Juventude': 'Juventude',
    'Flamengo': 'Flamengo',
    'Vitória': 'Vitória',
    'Bahia': 'Bahia',
    'Fluminense': 'Fluminense',
    'Fortaleza': 'Fortaleza',
    'Atlético PR': 'Atlético PR',
    'São Paulo': 'São Paulo',
    'Palmeiras': 'Palmeiras',
    'Bragantino': 'Bragantino',
    'Corinthians': 'Corinthians',
    'Avaí': 'Avaí',
    'CSA': 'CSA',
    'Grêmio': 'Grêmio',
    'Internacional': 'Internacional',
    'Criciúma': 'Criciúma',
    'Cruzeiro': 'Cruzeiro'
}

# Dicionário com os times do Brasileirão Série B
brasileirao_b_teams = {
    'Remo': 'Remo',
    'Vila Nova': 'Vila Nova',
    'Operário PR': 'Operário PR',
    'Botafogo SP': 'Botafogo SP',
    'Chapecoense': 'Chapecoense',
    'CSA': 'CSA',
    'Oeste': 'Oeste',
    'Juventude': 'Juventude',
    'Brasil de Pelotas': 'Brasil de Pelotas',
    'Bragantino': 'Bragantino',
    'Boa': 'Boa',
    'Mirassol': 'Mirassol',
    'Sampaio Corrêa': 'Sampaio Corrêa',
    'Vasco da Gama': 'Vasco da Gama',
    'Grêmio': 'Grêmio',
    'Criciúma': 'Criciúma',
    'Ituano': 'Ituano',
    'Figueirense': 'Figueirense',
    'Avaí': 'Avaí',
    'Goiás': 'Goiás',
    'Santa Cruz': 'Santa Cruz',
    'Fortaleza': 'Fortaleza',
    'São Bento': 'São Bento',
    'Ceará': 'Ceará',
    'Novorizontino': 'Novorizontino',
    'Londrina': 'Londrina',
    'Confiança': 'Confiança',
    'Brusque': 'Brusque',
    'Luverdense': 'Luverdense',
    'Guarani': 'Guarani',
    'Sport Recife': 'Sport Recife',
    'Atlético GO': 'Atlético GO',
    'Cuiabá': 'Cuiabá',
    'Tombense': 'Tombense',
    'Bahia': 'Bahia',
    'América Mineiro': 'América Mineiro',
    'Coritiba': 'Coritiba',
    'Botafogo': 'Botafogo',
    'Paysandu': 'Paysandu',
    'Internacional': 'Internacional',
    'Náutico': 'Náutico',
    'Vitória': 'Vitória',
    'Cruzeiro': 'Cruzeiro',
    'Paraná': 'Paraná',
    'CRB': 'CRB',
    'Ponte Preta': 'Ponte Preta',
    'ABC': 'ABC'
}

# Lista  com as features
features = [
    "Pre-Match PPG (Home)",
    "Pre-Match PPG (Away)", 
    "home_ppg", 
    "away_ppg", 
    "home_team_corner_count", 
    "away_team_corner_count", 
    "home_team_shots", 
    "away_team_shots", 
    "home_team_shots_on_target", 
    "away_team_shots_on_target", 
    "home_team_shots_off_target", 
    "away_team_shots_off_target", 
    "home_team_fouls", 
    "away_team_fouls", 
    "home_team_possession", 
    "away_team_possession", 
    "Home Team Pre-Match xG", 
    "Away Team Pre-Match xG", 
    "team_a_xg", 
    "team_b_xg", 
    "average_goals_per_match_pre_match", 
    "btts_percentage_pre_match",
    "average_corners_per_match_pre_match", 
    "average_cards_per_match_pre_match", 
    "odds_ft_home_team_win", 
    "odds_ft_draw", 
    "odds_ft_away_team_win", 
    "odds_btts_yes", 
    "odds_btts_no",
    "home_goals_scored_rolling_avg",
    "home_goals_conceded_rolling_avg",
    "away_goals_scored_rolling_avg",
    "away_goals_conceded_rolling_avg",
]
